name: Generate Content Script

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: nightly
    - name: Generate content
      run: cargo run --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: Content Script
        path: output.txt
